# Generated by Django 5.0.1 on 2024-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHAT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_f_name', models.CharField(max_length=18)),
                ('f_l_name', models.CharField(max_length=18)),
                ('f_birthdate', models.DateField()),
                ('f_email', models.CharField(max_length=25)),
                ('f_phone', models.CharField(max_length=12)),
                ('mate_f_name', models.CharField(max_length=18)),
                ('mate_l_name', models.CharField(max_length=18)),
                ('mate_birthdate', models.DateField()),
                ('mate_email', models.CharField(max_length=25)),
                ('mate_phone', models.CharField(max_length=12)),
                ('mate_u_name', models.CharField(max_length=25)),
                ('mate_link', models.CharField(max_length=50)),
                ('mate_other', models.CharField(max_length=400)),
                ('finder', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='other',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
